"""add_pending_events

Revision ID: ab717e9c5282
Revises: 
Create Date: 2026-08-26 19:11:07.793414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab717e9c5282'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_external_id'), 'employees', ['external_id'], unique=True)
    op.create_index(op.f('ix_employees_telegram_user_id'), 'employees', ['telegram_user_id'], unique=True)
    op.create_table('notification_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at_external', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at_external', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_external_id'), 'orders', ['external_id'], unique=True)
    op.create_table('pending_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('extracted_reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_events_chat_id'), 'pending_events', ['chat_id'], unique=False)
    op.create_index(op.f('ix_pending_events_message_id'), 'pending_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_pending_events_status'), 'pending_events', ['status'], unique=False)
    op.create_index(op.f('ix_pending_events_telegram_user_id'), 'pending_events', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_pending_events_ticket_number'), 'pending_events', ['ticket_number'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('postponements_detected', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installations_employee_id'), 'installations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_installations_external_id'), 'installations', ['external_id'], unique=True)
    op.create_index(op.f('ix_installations_order_id'), 'installations', ['order_id'], unique=False)
    op.create_index(op.f('ix_installations_scheduled_date'), 'installations', ['scheduled_date'], unique=False)
    op.create_table('sync_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sync_run_id', sa.Uuid(), nullable=False),
    sa.Column('order_external_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_errors_sync_run_id'), 'sync_errors', ['sync_run_id'], unique=False)
    op.create_table('installation_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_date', sa.Date(), nullable=True),
    sa.Column('new_date', sa.Date(), nullable=True),
    sa.Column('old_employee_id', sa.Uuid(), nullable=True),
    sa.Column('new_employee_id', sa.Uuid(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('change_source', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_history_event_id'), 'installation_history', ['event_id'], unique=False)
    op.create_index(op.f('ix_installation_history_installation_id'), 'installation_history', ['installation_id'], unique=False)
    op.create_table('postponements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('old_date', sa.Date(), nullable=True),
    sa.Column('new_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reason_category', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postponements_detected_at'), 'postponements', ['detected_at'], unique=False)
    op.create_index(op.f('ix_postponements_employee_id'), 'postponements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_postponements_event_id'), 'postponements', ['event_id'], unique=False)
    op.create_index(op.f('ix_postponements_installation_id'), 'postponements', ['installation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postponements_installation_id'), table_name='postponements')
    op.drop_index(op.f('ix_postponements_event_id'), table_name='postponements')
    op.drop_index(op.f('ix_postponements_employee_id'), table_name='postponements')
    op.drop_index(op.f('ix_postponements_detected_at'), table_name='postponements')
    op.drop_table('postponements')
    op.drop_index(op.f('ix_installation_history_installation_id'), table_name='installation_history')
    op.drop_index(op.f('ix_installation_history_event_id'), table_name='installation_history')
    op.drop_table('installation_history')
    op.drop_index(op.f('ix_sync_errors_sync_run_id'), table_name='sync_errors')
    op.drop_table('sync_errors')
    op.drop_index(op.f('ix_installations_scheduled_date'), table_name='installations')
    op.drop_index(op.f('ix_installations_order_id'), table_name='installations')
    op.drop_index(op.f('ix_installations_external_id'), table_name='installations')
    op.drop_index(op.f('ix_installations_employee_id'), table_name='installations')
    op.drop_table('installations')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_pending_events_ticket_number'), table_name='pending_events')
    op.drop_index(op.f('ix_pending_events_telegram_user_id'), table_name='pending_events')
    op.drop_index(op.f('ix_pending_events_status'), table_name='pending_events')
    op.drop_index(op.f('ix_pending_events_message_id'), table_name='pending_events')
    op.drop_index(op.f('ix_pending_events_chat_id'), table_name='pending_events')
    op.drop_table('pending_events')
    op.drop_index(op.f('ix_orders_external_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_employees_telegram_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_external_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
